# Strict-lp64 compiler runtime generated by Zig.

COMPILER_RT_SRC = user/runtime/compiler_rt.zig
COMPILER_RT_OUT = $(USER_OUTROOT)/runtime
COMPILER_RT_A   = $(COMPILER_RT_OUT)/libcompiler_rt.a

$(COMPILER_RT_A): $(COMPILER_RT_SRC)
	$(QUIET_MUSL)
	$(Q)command -v $(ZIG) >/dev/null 2>&1 || { \
		echo "ERROR: Zig 0.16 or newer is required for the BusyBox profile." >&2; \
		exit 1; \
	}
	$(Q)major=$$($(ZIG) version | cut -d. -f1); \
	minor=$$($(ZIG) version | cut -d. -f2); \
	if [ "$$major" -lt 1 ] && [ "$$minor" -lt 16 ]; then \
		echo "ERROR: Zig 0.16 or newer is required; found $$($(ZIG) version)." >&2; \
		exit 1; \
	fi
	$(Q)mkdir -p $(dir $@)
	$(Q)$(ZIG) build-lib $< -target riscv64-freestanding \
		-mcpu=generic_rv64+m+a+c -OReleaseSmall -fcompiler-rt -static \
		-femit-bin=$(abspath $@)
