#ifndef _CUTEOS_UAPI_MEMBARRIER_H
#define _CUTEOS_UAPI_MEMBARRIER_H

/*
 * Linux membarrier(2) UAPI command values.
 */

#define MEMBARRIER_CMD_QUERY				    0
#define MEMBARRIER_CMD_GLOBAL				    (1 << 0)
#define MEMBARRIER_CMD_GLOBAL_EXPEDITED			    (1 << 1)
#define MEMBARRIER_CMD_REGISTER_GLOBAL_EXPEDITED	    (1 << 2)
#define MEMBARRIER_CMD_PRIVATE_EXPEDITED		    (1 << 3)
#define MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED	    (1 << 4)
#define MEMBARRIER_CMD_PRIVATE_EXPEDITED_SYNC_CORE	    (1 << 5)
#define MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED_SYNC_CORE (1 << 6)
#define MEMBARRIER_CMD_PRIVATE_EXPEDITED_RSEQ		    (1 << 7)
#define MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED_RSEQ	    (1 << 8)
#define MEMBARRIER_CMD_GET_REGISTRATIONS		    (1 << 9)

#define MEMBARRIER_CMD_SHARED MEMBARRIER_CMD_GLOBAL

#define MEMBARRIER_CMD_FLAG_CPU (1 << 0)

#endif
